### ISSUE TITLE
No module named 'mask2camouflage.modeling.transformer_decoder.meanshift_attention'

### ISSUE THREAD

**Issue by wchchw** [underlmao/Mask2Camouflage#1]
Thanks to the author for his contribution. I have this error when I use it, and I didn't find “meanshift_attention”.
I look forward to your reply. Thank you！

root@autodl-container-a2ab40b635-1ac793ef:~/autodl-tmp/Mask2Camouflage-main# python train_net.py --config-file configs/CIS-R50.yaml --eval-only MODEL.WEIGHTS output-cod10k-resnet50/model_0099999.pth
Traceback (most recent call last):
  File "train_net.py", line 32, in <module>
    from mask2camouflage import (
  File "/root/autodl-tmp/Mask2Camouflage-main/mask2camouflage/__init__.py", line 2, in <module>
    from . import modeling
  File "/root/autodl-tmp/Mask2Camouflage-main/mask2camouflage/modeling/__init__.py", line 2, in <module>
    from .transformer_decoder.mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoderFASeg, MultiScaleMaskedTransformerDecoder
  File "/root/autodl-tmp/Mask2Camouflage-main/mask2camouflage/modeling/transformer_decoder/__init__.py", line 3, in <module>
    from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder, MultiScaleMaskedTransformerDecoderFASeg
  File "/root/autodl-tmp/Mask2Camouflage-main/mask2camouflage/modeling/transformer_decoder/mask2former_transformer_decoder.py", line 17, in <module>
    from .meanshift_attention import MeanShiftAttention
ModuleNotFoundError: No module named 'mask2camouflage.modeling.transformer_decoder.meanshift_attention'

**Comment by underlmao** [comment]
Hi, 
Thank you for your queries; please try to call the GlobalShiftAttention from the "globalshift_attention.py" file instead. I have updated the code the make sure it works.
